services:
  postgres:
    image: postgres:15
    container_name: speaker-postgres
    environment:
      POSTGRES_DB: tedtalksdb
    env_file:
      - src/main/resources/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
